#include "anim_idle.inc.c"
#include "anim_ArmatureAction.inc.c"
#include "anim_walk.inc.c"
#include "anim_jump.inc.c"
#include "anim_dash.inc.c"
#include "anim_down.inc.c"
#include "anim_FinalAttack1.inc.c"
#include "anim_summon.inc.c"
