extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl_Untitled_i8[];
extern u8 ccm_dl_sticky_ci4[];
extern u8 ccm_dl_sticky_pal_rgba16[];
extern Vtx ccm_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx ccm_dl_Cube_mesh_layer_5_vtx_0[53];
extern Gfx ccm_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_0[16];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_f3dlite_material_001[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_001[];
extern Gfx mat_ccm_dl_f3dlite_material[];
extern Gfx mat_revert_ccm_dl_f3dlite_material[];
extern Gfx ccm_dl_Cube_mesh_layer_5[];
extern Gfx ccm_dl_Cube_mesh_layer_1[];
