extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl_hypertube_ci4[];
extern u8 ccm_dl_hypertube_pal_rgba16[];
extern u8 ccm_dl_Untitled_i8[];
extern u8 ccm_dl_sticky_ci4[];
extern u8 ccm_dl_sticky_pal_rgba16[];
extern u8 ccm_dl_Untitled_001_i8[];
extern u8 ccm_dl_Untitled_002_i8[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_0[118];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx ccm_dl_Cube_mesh_layer_5_vtx_0[338];
extern Gfx ccm_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_0[64];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_1[8];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_2[6];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_2[];
extern Gfx mat_ccm_dl_f3dlite_material_003[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_003[];
extern Gfx mat_ccm_dl_f3dlite_material_001[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_001[];
extern Gfx mat_ccm_dl_f3dlite_material_002[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_002[];
extern Gfx mat_ccm_dl_death1[];
extern Gfx mat_revert_ccm_dl_death1[];
extern Gfx mat_ccm_dl_death2[];
extern Gfx mat_revert_ccm_dl_death2[];
extern Gfx ccm_dl_Circle_mesh_layer_1[];
extern Gfx ccm_dl_Cube_mesh_layer_5[];
extern Gfx ccm_dl_Cube_mesh_layer_1[];
