extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl__1_f3d_001_lights;
extern Lights1 castle_grounds_dl__2_f3d_001_lights;
extern u8 castle_grounds_dl_DFBfZv_I_400x400_rgba16[];
extern u8 castle_grounds_dl__1_rgba16[];
extern u8 castle_grounds_dl_bluesand_ci8[];
extern u8 castle_grounds_dl_bluesand_pal_rgba16[];
extern Vtx castle_grounds_dl_AkuroFace_mesh_layer_1_vtx_0[128];
extern Gfx castle_grounds_dl_AkuroFace_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_TESTOW_mesh_layer_1_vtx_0[729];
extern Gfx castle_grounds_dl_TESTOW_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_TESTOW_mesh_layer_1_vtx_1[536];
extern Gfx castle_grounds_dl_TESTOW_mesh_layer_1_tri_1[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_castle_grounds_dl__1_f3d_001[];
extern Gfx mat_castle_grounds_dl__2_f3d_001[];
extern Gfx mat_revert_castle_grounds_dl__2_f3d_001[];
extern Gfx castle_grounds_dl_AkuroFace_mesh_layer_1[];
extern Gfx castle_grounds_dl_TESTOW_mesh_layer_1[];
