extern const GeoLayout rl_ccmhangroll_geo[];
extern u8 rl_ccmhangroll_hang_ci4[];
extern u8 rl_ccmhangroll_hang_pal_rgba16[];
extern u8 rl_ccmhangroll_out_side_ci4[];
extern u8 rl_ccmhangroll_out_side_pal_rgba16[];
extern Vtx rl_ccmhangroll_rl_ccmhangroll_mesh_layer_1_vtx_cull[8];
extern Vtx rl_ccmhangroll_rl_ccmhangroll_mesh_layer_1_vtx_0[40];
extern Gfx rl_ccmhangroll_rl_ccmhangroll_mesh_layer_1_tri_0[];
extern Vtx rl_ccmhangroll_rl_ccmhangroll_mesh_layer_1_vtx_1[47];
extern Gfx rl_ccmhangroll_rl_ccmhangroll_mesh_layer_1_tri_1[];
extern Gfx mat_rl_ccmhangroll_f3dlite_material_001[];
extern Gfx mat_revert_rl_ccmhangroll_f3dlite_material_001[];
extern Gfx mat_rl_ccmhangroll_f3dlite_material[];
extern Gfx mat_revert_rl_ccmhangroll_f3dlite_material[];
extern Gfx rl_ccmhangroll_rl_ccmhangroll_mesh_layer_1[];
