#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"

#include "mist/geo.inc.c"
#include "explosion/geo.inc.c"
#include "butterfly/geo.inc.c"
#include "coin/geo.inc.c"
#include "warp_pipe/geo.inc.c"
#include "door/geo.inc.c"
#include "bowser_key/geo.inc.c"
#include "flame/geo.inc.c"
#include "blue_fish/geo.inc.c"
#include "leaves/geo.inc.c"
#include "mario_cap/geo.inc.c"
#include "number/geo.inc.c"
#include "mushroom_1up/geo.inc.c"
#include "star/geo.inc.c"
#include "dirt/geo.inc.c"
#include "transparent_star/geo.inc.c"
#include "white_particle/geo.inc.c"
#include "wooden_signpost/geo.inc.c"
#include "tree/geo.inc.c"

#include "redSwitchBlock/geo.inc.c"
#include "blueSwitchBlock/geo.inc.c"
#include "redSwitchBlockSwitch/geo.inc.c"
#include "blueSwitchBlockSwitch/geo.inc.c"
#include "purpleShiftPlatform/geo.inc.c"
#include "yellowShiftPlatform/geo.inc.c"
#include "curFlashingBlock/geo.inc.c"
#include "nextFlashingBlock/geo.inc.c"
#include "launchSpring/geo.inc.c"
#include "rotationBox/geo.inc.c"
#include "rl180rotate/geo.inc.c"
#include "movingwall/geo.inc.c"
#include "barrelJet/geo.inc.c"
#include "barrelJetRed/geo.inc.c"
#include "barrelJetYellow/geo.inc.c"
#include "barrelSpeedUp/geo.inc.c"
#include "barrelSpeedDown/geo.inc.c"

#include "rlbridge/geo.inc.c"
#include "rlsquarefloating/geo.inc.c"
#include "rlexelevator/geo.inc.c"