extern const GeoLayout rl_top2_geo[];
extern u8 rl_top2_Untitled_ci4[];
extern u8 rl_top2_Untitled_x_blue_tex1_pal_rgba16[];
extern u8 rl_top2_blue_tex1_ci4[];
extern Vtx rl_top2_rl_top2_mesh_layer_6_vtx_cull[8];
extern Vtx rl_top2_rl_top2_mesh_layer_6_vtx_0[316];
extern Gfx rl_top2_rl_top2_mesh_layer_6_tri_0[];
extern Gfx mat_rl_top2_f3dlite_material_001_layer6[];
extern Gfx mat_revert_rl_top2_f3dlite_material_001_layer6[];
extern Gfx rl_top2_rl_top2_mesh_layer_6[];
