extern const GeoLayout rlmetalbox_geo[];
extern u8 rlmetalbox_metal_box_ci8[];
extern u8 rlmetalbox_metal_box_pal_rgba16[];
extern u8 rlmetalbox__14_invisible_ia8[];
extern Vtx rlmetalbox_rlmetalbox_mesh_layer_1_vtx_cull[8];
extern Vtx rlmetalbox_rlmetalbox_mesh_layer_1_vtx_0[24];
extern Gfx rlmetalbox_rlmetalbox_mesh_layer_1_tri_0[];
extern Vtx rlmetalbox_rlmetalbox_mesh_layer_5_vtx_cull[8];
extern Vtx rlmetalbox_rlmetalbox_mesh_layer_5_vtx_0[20];
extern Gfx rlmetalbox_rlmetalbox_mesh_layer_5_tri_0[];
extern Gfx mat_rlmetalbox_bomb[];
extern Gfx mat_revert_rlmetalbox_bomb[];
extern Gfx mat_rlmetalbox_f3dlite_material[];
extern Gfx mat_revert_rlmetalbox_f3dlite_material[];
extern Gfx rlmetalbox_rlmetalbox_mesh_layer_1[];
extern Gfx rlmetalbox_rlmetalbox_mesh_layer_5[];
