extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_Default_Material_f3d_lights;
extern Lights1 bob_dl__1_f3d_lights;
extern Lights1 bob_dl__2_f3d_lights;
extern Lights1 bob_dl__3_f3d_lights;
extern Lights1 bob_dl__4_f3d_lights;
extern Lights1 bob_dl__5_f3d_lights;
extern Lights1 bob_dl__6_f3d_lights;
extern Lights1 bob_dl__7_f3d_lights;
extern u8 bob_dl__1_rgba16[];
extern u8 bob_dl__2_rgba16[];
extern u8 bob_dl__3_rgba16[];
extern u8 bob_dl__4_rgba16[];
extern u8 bob_dl__5_rgba16[];
extern u8 bob_dl__6_rgba16[];
extern u8 bob_dl__7_rgba16[];
extern Vtx bob_dl_C1_mesh_layer_1_vtx_0[67];
extern Gfx bob_dl_C1_mesh_layer_1_tri_0[];
extern Vtx bob_dl_C1_mesh_layer_1_vtx_1[3560];
extern Gfx bob_dl_C1_mesh_layer_1_tri_1[];
extern Vtx bob_dl_C1_mesh_layer_1_vtx_2[991];
extern Gfx bob_dl_C1_mesh_layer_1_tri_2[];
extern Vtx bob_dl_C1_mesh_layer_1_vtx_3[349];
extern Gfx bob_dl_C1_mesh_layer_1_tri_3[];
extern Vtx bob_dl_C1_mesh_layer_1_vtx_4[1140];
extern Gfx bob_dl_C1_mesh_layer_1_tri_4[];
extern Vtx bob_dl_C1_mesh_layer_1_vtx_5[51];
extern Gfx bob_dl_C1_mesh_layer_1_tri_5[];
extern Vtx bob_dl_C1_mesh_layer_1_vtx_6[265];
extern Gfx bob_dl_C1_mesh_layer_1_tri_6[];
extern Vtx bob_dl_C1_mesh_layer_1_vtx_7[8];
extern Gfx bob_dl_C1_mesh_layer_1_tri_7[];
extern Gfx mat_bob_dl_Default_Material_f3d[];
extern Gfx mat_bob_dl__1_f3d[];
extern Gfx mat_bob_dl__2_f3d[];
extern Gfx mat_bob_dl__3_f3d[];
extern Gfx mat_bob_dl__4_f3d[];
extern Gfx mat_bob_dl__5_f3d[];
extern Gfx mat_bob_dl__6_f3d[];
extern Gfx mat_bob_dl__7_f3d[];
extern Gfx bob_dl_C1_mesh_layer_1[];
