extern const GeoLayout rl_burnbridge_geo[];
extern u8 rl_burnbridge_rl_burnbridge_CI4_ci4[];
extern u8 rl_burnbridge_rl_burnbridge_CI4_x_rl_burnbridge02_CI4_pal_rgba16[];
extern u8 rl_burnbridge_rl_burnbridge02_CI4_ci4[];
extern Vtx rl_burnbridge_rl_burnbridge_mesh_layer_1_vtx_cull[8];
extern Vtx rl_burnbridge_rl_burnbridge_mesh_layer_1_vtx_0[24];
extern Gfx rl_burnbridge_rl_burnbridge_mesh_layer_1_tri_0[];
extern Gfx mat_rl_burnbridge_f3dlite_material_layer1[];
extern Gfx mat_revert_rl_burnbridge_f3dlite_material_layer1[];
extern Gfx rl_burnbridge_rl_burnbridge_mesh_layer_1[];
