extern const GeoLayout rlbridge_geo[];
extern u8 rlbridge_floor_ci8[];
extern u8 rlbridge_floor_pal_rgba16[];
extern Vtx rlbridge_rlbridge_mesh_layer_1_vtx_cull[8];
extern Vtx rlbridge_rlbridge_mesh_layer_1_vtx_0[20];
extern Gfx rlbridge_rlbridge_mesh_layer_1_tri_0[];
extern Vtx rlbridge_rlbridge_mesh_layer_1_vtx_1[4];
extern Gfx rlbridge_rlbridge_mesh_layer_1_tri_1[];
extern Gfx mat_rlbridge_f3dlite_material_001[];
extern Gfx mat_revert_rlbridge_f3dlite_material_001[];
extern Gfx mat_rlbridge_f3dlite_material_slippery[];
extern Gfx mat_revert_rlbridge_f3dlite_material_slippery[];
extern Gfx rlbridge_rlbridge_mesh_layer_1[];
