extern const GeoLayout rl_hthazard_geo[];
extern u8 rl_hthazard_test_yellow_ci4[];
extern u8 rl_hthazard_test_yellow_pal_rgba16[];
extern Vtx rl_hthazard_rl_hthazard_mesh_layer_1_vtx_cull[8];
extern Vtx rl_hthazard_rl_hthazard_mesh_layer_1_vtx_0[16];
extern Gfx rl_hthazard_rl_hthazard_mesh_layer_1_tri_0[];
extern Vtx rl_hthazard_rl_hthazard_mesh_layer_1_vtx_1[10];
extern Gfx rl_hthazard_rl_hthazard_mesh_layer_1_tri_1[];
extern Gfx mat_rl_hthazard_f3dlite_material_001[];
extern Gfx mat_revert_rl_hthazard_f3dlite_material_001[];
extern Gfx mat_rl_hthazard_intangible[];
extern Gfx mat_revert_rl_hthazard_intangible[];
extern Gfx rl_hthazard_rl_hthazard_mesh_layer_1[];
