extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern u8 pss_dl__1_rgba16[];
extern u8 pss_dl__2_rgba16[];
extern u8 pss_dl__3_rgba16[];
extern u8 pss_dl__4_rgba16[];
extern u8 pss_dl__5_rgba16[];
extern u8 pss_dl__6_rgba16[];
extern Vtx pss_dl_PSS_v2_1_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_PSS_v2_1_mesh_layer_1_vtx_0[186];
extern Gfx pss_dl_PSS_v2_1_mesh_layer_1_tri_0[];
extern Vtx pss_dl_PSS_v2_1_mesh_layer_1_vtx_1[381];
extern Gfx pss_dl_PSS_v2_1_mesh_layer_1_tri_1[];
extern Vtx pss_dl_PSS_v2_1_mesh_layer_1_vtx_2[41];
extern Gfx pss_dl_PSS_v2_1_mesh_layer_1_tri_2[];
extern Vtx pss_dl_PSS_v2_1_mesh_layer_1_vtx_3[44];
extern Gfx pss_dl_PSS_v2_1_mesh_layer_1_tri_3[];
extern Vtx pss_dl_PSS_v2_1_mesh_layer_1_vtx_4[412];
extern Gfx pss_dl_PSS_v2_1_mesh_layer_1_tri_4[];
extern Vtx pss_dl_PSS_v2_1_mesh_layer_1_vtx_5[21];
extern Gfx pss_dl_PSS_v2_1_mesh_layer_1_tri_5[];
extern Gfx mat_pss_dl__1_f3d[];
extern Gfx mat_revert_pss_dl__1_f3d[];
extern Gfx mat_pss_dl__2_f3d[];
extern Gfx mat_revert_pss_dl__2_f3d[];
extern Gfx mat_pss_dl__3_f3d[];
extern Gfx mat_revert_pss_dl__3_f3d[];
extern Gfx mat_pss_dl__4_f3d[];
extern Gfx mat_revert_pss_dl__4_f3d[];
extern Gfx mat_pss_dl__5_f3d[];
extern Gfx mat_revert_pss_dl__5_f3d[];
extern Gfx mat_pss_dl__6_f3d[];
extern Gfx mat_revert_pss_dl__6_f3d[];
extern Gfx pss_dl_PSS_v2_1_mesh_layer_1[];
