extern const GeoLayout nextFlashingBlock_geo[];
extern u8 nextFlashingBlock__2_i8[];
extern u8 nextFlashingBlock__1_ci4[];
extern u8 nextFlashingBlock__1_pal_rgba16[];
extern Vtx nextFlashingBlock_nextFlashingBlock_mesh_layer_1_vtx_0[105];
extern Gfx nextFlashingBlock_nextFlashingBlock_mesh_layer_1_tri_0[];
extern Vtx nextFlashingBlock_nextFlashingBlock_mesh_layer_1_vtx_1[24];
extern Gfx nextFlashingBlock_nextFlashingBlock_mesh_layer_1_tri_1[];
extern Gfx mat_nextFlashingBlock__1_001_f3d[];
extern Gfx mat_revert_nextFlashingBlock__1_001_f3d[];
extern Gfx mat_nextFlashingBlock__2_001_f3d[];
extern Gfx mat_revert_nextFlashingBlock__2_001_f3d[];
extern Gfx nextFlashingBlock_nextFlashingBlock_mesh_layer_1[];
