extern const GeoLayout star_geo[];
extern Lights1 star__11_f3d_001_lights;
extern Lights1 star__1_f3d_lights;
extern u8 star__1_rgba16[];
extern Vtx star_LoveHeart_mesh_layer_1_vtx_0[192];
extern Gfx star_LoveHeart_mesh_layer_1_tri_0[];
extern Vtx star_LoveHeart_mesh_layer_1_vtx_1[202];
extern Gfx star_LoveHeart_mesh_layer_1_tri_1[];
extern Gfx mat_star__11_f3d_001[];
extern Gfx mat_star__1_f3d[];
extern Gfx star_LoveHeart_mesh_layer_1[];
