extern const GeoLayout movingwall_geo[];
extern Lights1 movingwall_f3dlite_material_002_lights;
extern Lights1 movingwall_f3dlite_material_lights;
extern u8 movingwall_wall01_ci8[];
extern u8 movingwall_wall01_pal_rgba16[];
extern u8 movingwall_floor_ci8[];
extern u8 movingwall_floor_pal_rgba16[];
extern Vtx movingwall_Cube_mesh_layer_1_vtx_0[24];
extern Gfx movingwall_Cube_mesh_layer_1_tri_0[];
extern Vtx movingwall_Cube_mesh_layer_1_vtx_1[8];
extern Gfx movingwall_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_movingwall_f3dlite_material_002[];
extern Gfx mat_revert_movingwall_f3dlite_material_002[];
extern Gfx mat_movingwall_f3dlite_material[];
extern Gfx mat_revert_movingwall_f3dlite_material[];
extern Gfx movingwall_Cube_mesh_layer_1[];
