extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern Vtx lll_dl__Icosphere2_mesh_layer_1_vtx_0[240];
extern Gfx lll_dl__Icosphere2_mesh_layer_1_tri_0[];
extern Vtx lll_dl__Icosphere2_001_mesh_layer_1_vtx_0[240];
extern Gfx lll_dl__Icosphere2_001_mesh_layer_1_tri_0[];
extern Vtx lll_dl__p_mesh_layer_1_vtx_0[4];
extern Gfx lll_dl__p_mesh_layer_1_tri_0[];
extern Gfx mat_lll_dl_f3dlite_material[];
extern Gfx mat_lll_dl_f3dlite_material_002[];
extern Gfx mat_lll_dl_f3dlite_material_001[];
extern Gfx mat_revert_lll_dl_f3dlite_material_001[];
extern Gfx lll_dl__Icosphere2_mesh_layer_1[];
extern Gfx lll_dl__Icosphere2_001_mesh_layer_1[];
extern Gfx lll_dl__p_mesh_layer_1[];
