extern const GeoLayout rl_ccm90degree_geo[];
extern u8 rl_ccm90degree_hang_ci4[];
extern u8 rl_ccm90degree_hang_pal_rgba16[];
extern u8 rl_ccm90degree_top_ci8[];
extern u8 rl_ccm90degree_top_pal_rgba16[];
extern Vtx rl_ccm90degree_rl_ccm90degree_mesh_layer_1_vtx_cull[8];
extern Vtx rl_ccm90degree_rl_ccm90degree_mesh_layer_1_vtx_0[5];
extern Gfx rl_ccm90degree_rl_ccm90degree_mesh_layer_1_tri_0[];
extern Vtx rl_ccm90degree_rl_ccm90degree_mesh_layer_1_vtx_1[149];
extern Gfx rl_ccm90degree_rl_ccm90degree_mesh_layer_1_tri_1[];
extern Gfx mat_rl_ccm90degree_f3dlite_material_001[];
extern Gfx mat_revert_rl_ccm90degree_f3dlite_material_001[];
extern Gfx mat_rl_ccm90degree_super__slippery[];
extern Gfx mat_revert_rl_ccm90degree_super__slippery[];
extern Gfx rl_ccm90degree_rl_ccm90degree_mesh_layer_1[];
